all:
     swig -python -c++ -o bids.cpp squirrelDataDictionary.cpp squirrelImageIO.cpp squirrelGroupAnalysis.cpp utils.cpp convert.cpp dicom.cpp main.cpp squirrel.cpp squirrelAnalysis.cpp squirrelDrug.cpp squirrelExperiment.cpp squirrelMeasure.cpp squirrelPipeline.cpp squirrelSeries.cpp squirrelStudy.cpp squirrelSubject.cpp validate.cpp squirrel.i
     python setup.py build_ext --inplace